version: '3.4'

services:
  californianhealth.database:
    container_name: californianhealth.database
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
       - ACCEPT_EULA=Y
       - MSSQL_SA_PASSWORD=Passw0rd!
    volumes:
       - sqlserver_data:/var/opt/mssql
    ports:
      - 8001:1433
  
  californianhealth.webapis.gateway:
    container_name: californianhealth.webapis.gateway
    image: ${DOCKER_REGISTRY-}californianhealthwebapisgateway
    build:
      context: .
      dockerfile: CalifornianHealth.WebAPIs.Gateway/Dockerfile
    ports:
      - 5020:80
      - 7055:443
    depends_on:
      - californianhealth.database

  californianhealth.webapis.doctors:
    container_name: californianhealth.webapis.doctors
    image: ${DOCKER_REGISTRY-}californianhealthwebapisdoctors
    build:
      context: .
      dockerfile: CalifornianHealth.WebAPIs.Doctors/Dockerfile
    ports:
      - 5013:80
      - 7090:443
    depends_on:
      - californianhealth.database

  californianhealth.webapis.calendar:
    container_name: californianhealth.webapis.calendar
    image: ${DOCKER_REGISTRY-}californianhealthwebapiscalendar
    build:
      context: .
      dockerfile: CalifornianHealth.WebAPIs.Calendar/Dockerfile
    ports:
      - 5234:80
      - 7207:443
    depends_on:
      - californianhealth.database
  
  californianhealth.userinterface:
    container_name: UserInterface
    image: ${DOCKER_REGISTRY-}californianhealthuserinterface
    build:
      context: .
      dockerfile: CalifornianHealth.UserInterface/Dockerfile
    ports:
      - 5110:80
      - 7153:443
    depends_on:
      - californianhealth.webapis.gateway
      - californianhealth.webapis.doctors
      - californianhealth.webapis.calendar

volumes:
  sqlserver_data:

